version: '3.8'
services:
  ai:
    build:
      context: .
      dockerfile: Dockerfile
      target: flask
    ports:
      - "8080:8080"
    networks:
      - app-network
    env_file:
      - .env
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - ai
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "5050:5050"
    networks:
      - app-network
    env_file:
      - .env
    depends_on:
      - ai

networks:
  app-network:
    driver: bridge
